EXTRACTION_SCHEMAS = {
    "invoice": {
        "vendor": {"name": "string", "address": "string|null", "tax_id": "string|null", "email": "string|null"},
        "invoice_number": "string",
        "invoice_date": "ISO 8601 date",
        "due_date": "ISO 8601 date|null",
        "currency": "3-letter currency code",
        "subtotal": "number",
        "tax_amount": "number|null",
        "discount_amount": "number|null",
        "total_amount": "number",
        "payment_terms": "string|null",
        "line_items": [{"description": "string", "quantity": "number", "unit_price": "number", "total": "number"}],
        "notes": "string|null",
    },
    "receipt": {
        "merchant": {"name": "string", "address": "string|null"},
        "date": "ISO 8601 datetime",
        "items": [{"description": "string", "quantity": "number", "price": "number"}],
        "subtotal": "number",
        "tax": "number|null",
        "tip": "number|null",
        "total": "number",
        "payment_method": "string|null",
        "currency": "3-letter currency code",
    },
    "bank_statement": {
        "bank_name": "string",
        "account_holder": "string",
        "account_number": "last 4 digits only",
        "account_type": "string",
        "currency": "string",
        "period": {"start": "ISO 8601 date", "end": "ISO 8601 date"},
        "opening_balance": "number",
        "closing_balance": "number",
        "total_deposits": "number",
        "total_withdrawals": "number",
        "transactions": [{"date": "ISO 8601 date", "description": "string", "amount": "number", "balance": "number|null"}],
    },
    "generic": {
        "title": "string|null",
        "date": "ISO 8601 date|null",
        "parties": ["list of names/entities"],
        "key_values": {"key": "value pairs of important data"},
        "summary": "brief description",
    },
}
